#!/usr/bin/perl

use strict;
use warnings;

use Text::CSV;
use JSON;
use DateTime;
use Data::Dump qw(dump);

my $author_posts = {};
my $subreddits = {};

my $count = 0;

{
	my $json;
	{
		local $/;
		open my $fh, "<", "daySubredditBreakdown-transformed.json";
		$json = <$fh>;
		close $fh;
	}

	my $json_data = decode_json($json);

	foreach (@$json_data) {
		$subreddits->{$_->{'key'}} = ();
		$count++;
		#last if $count >= 50;
	}
}

my $csv = Text::CSV->new({ sep_char => ',' });
{
	open my $fh, "<", "posts.csv" or die "File could not be opened: $!\n";
	while (my $line = <$fh>) {
		$csv->parse($line) or die "Line could not be parsed: $line\n";
		my @fields = $csv->fields();
		if (exists $subreddits->{$fields[1]}) {
			$author_posts->{$fields[0]}->{$fields[1]} += 1;
		}
	}
	close $fh;
}

print "Processing data.\n";

foreach (keys %$author_posts) {
	my @author_subreddits = sort keys %{ $author_posts->{$_} };
	for (my $i = 0; $i < scalar @author_subreddits; $i++) {
		for (my $j = $i + 1; $j < scalar @author_subreddits; $j++) {
			$subreddits->{$author_subreddits[$i]}->{$author_subreddits[$j]} += $author_posts->{$_}->{$author_subreddits[$i]};
		}
	}
}

{
	open my $fh, ">", "subreddits-list.csv";

	my @headers = ("name", "color");
	$csv->combine(@headers);
	print $fh $csv->string() . "\n";

	my @colorPortions = ("79", "F2", "DA", "A9");
	for my $sub (sort keys %$subreddits) {
		my @row;
		push(@row, $sub);
		push(@row, "#" . $colorPortions[rand(scalar @colorPortions)] . $colorPortions[rand(scalar @colorPortions)] . $colorPortions[rand(scalar @colorPortions)]);
		$csv->combine(@row);
		print $fh $csv->string() . "\n";
	}
	close $fh;
}


{
	my @rows;
	for my $sub1 (sort keys %$subreddits) {
		my @row;
		for my $sub2 (sort keys %$subreddits) {
			if (exists $subreddits->{$sub1}->{$sub2}) {
				push(@row, $subreddits->{$sub1}->{$sub2});
			} else {
				push(@row, $subreddits->{$sub2}->{$sub1});
			}
		}
		push(@rows, \@row);
	}
	open my $fh, ">", "posts-adjacency-matrix.csv";
	print $fh JSON::to_json(\@rows, {utf8 => 1, pretty => 1});
	close $fh;
}
