#!/usr/bin/perl

use strict;
use warnings;

use JSON;
use DateTime;

my $json;
{
	local $/;
	open my $fh, "<", "daySubredditBreakdown-testing.json";
	$json = <$fh>;
	close $fh;
}

my $json_data = decode_json($json);

my $json_subreddits = {};

foreach (@{ $json_data }) {
	if (not $json_subreddits->{$_->{'subreddit'}}) {
		$json_subreddits->{$_->{'subreddit'}} = {};
		$json_subreddits->{$_->{'subreddit'}}->{'key'} = $_->{'subreddit'};
		$json_subreddits->{$_->{'subreddit'}}->{'values'} = [];
	}
	my @dayCountArray;
	my $date = DateTime->new(
		year => 2015,
		month => 5,
		day => $_->{'createdDay'},
	);
	push(@dayCountArray, $date->epoch);
	push(@dayCountArray, $_->{'countPosts'} + 0);
	push(@{ $json_subreddits->{$_->{'subreddit'}}->{'values'} }, \@dayCountArray)
}

my $json_resp = [];

foreach (keys %$json_subreddits) {
	push(@{ $json_resp }, $json_subreddits->{$_});
}

my $json_response = JSON::to_json($json_resp, {utf8 => 1, pretty => 1});
{
	open my $fh, ">", "daySubredditBreakdown-testing-transformed.json";
	print $fh $json_response;
	close $fh;
}
