#!/usr/bin/perl

use strict;
use warnings;

use JSON;
use DateTime;

my $json;
{
	local $/;
	open my $fh, "<", "daySubredditBreakdown.json";
	$json = <$fh>;
	close $fh;
}

my $json_data = decode_json($json);

my $json_subreddits = {};

my $days = {};

foreach (@{ $json_data }) {
	if (not $json_subreddits->{$_->{'subreddit'}}) {
		$json_subreddits->{$_->{'subreddit'}} = {};
		$json_subreddits->{$_->{'subreddit'}}->{'key'} = $_->{'subreddit'};
		$json_subreddits->{$_->{'subreddit'}}->{'values'} = [];
		$json_subreddits->{$_->{'subreddit'}}->{'valuesHash'} = {};
	}
	my @dayCountArray;
	my $date = DateTime->new(
		year => 2015,
		month => 5,
		day => $_->{'createdDay'},
	);
	push(@dayCountArray, $date->epoch);
	$days->{$date->epoch} = ();
	$json_subreddits->{$_->{'subreddit'}}->{'valuesHash'}->{$date->epoch} = $_->{'countPosts'} + 0;
}

my $json_resp = [];

foreach (keys %$json_subreddits) {
	foreach my $dayCount (keys %{ $json_subreddits->{$_}->{'valuesHash'} }) {
		my @dayCountArray;
		push(@dayCountArray, $dayCount);
		push(@dayCountArray, $json_subreddits->{$_}->{'valuesHash'}->{$dayCount});
		push(@{ $json_subreddits->{$_}->{'values'} }, \@dayCountArray);
	}
	foreach my $day (keys %$days) {
		if (not exists $json_subreddits->{$_}->{'valuesHash'}->{$day}) {
			my @dayCountArray;
			push(@dayCountArray, $day);
			push(@dayCountArray, 0);
			push(@{ $json_subreddits->{$_}->{'values'} }, \@dayCountArray);
		}
	}
	delete $json_subreddits->{$_}->{'valuesHash'};
	push(@{ $json_resp }, $json_subreddits->{$_});
}

my $json_response = JSON::to_json($json_resp, {utf8 => 1, pretty => 1});
{
	open my $fh, ">", "daySubredditBreakdown-transformed.json";
	print $fh $json_response;
	close $fh;
}
